### ISSUE TITLE
Add github action builds

### ISSUE THREAD

**Issue by Ruadhri17** [thin-edge/meta-tedge#10]
Add github action build that test if layer compiles and works as intended.

**Comment by Bravo555** [comment]
To add Github Action builds, I think I'd be necessary to research the following:

1. What CI processes are the other layer repositories using, if they do at all, the ones hosted on Github as well as elsewhere. Examples: poky, meta-openembedded, meta-rust, meta-rust-bin.
2. How to handle the space and compute requirements of building thin-edge in a Yocto environment. Proposed solutions are:
    1. build only the required package (thin-edge)
    2. cache the dependencies (build output of rust, cargo, and others)
    3. use [meta-rust-bin](https://github.com/rust-embedded/meta-rust-bin) to sidestep building of Rust completely

**Comment by Ruadhri17** [comment]
On Yocto Project summit from May 2022, There was a presentation on using Github Actions in Yocto layers. Here is link to the [video](https://www.youtube.com/watch?v=TsAcxd_acJI) and theirs [solution](https://github.com/DynamicDevices/meta-mono/blob/master/.github/workflows/CI_github.yml). I think we can create something similar. I noticed that if the dependencies are cached, next builds will be much faster. However, it will require some space and I don't know if we are allowed to use so much.

**Comment by reubenmiller** [comment]
Builds will be covered by the meta-tedge-project repository: https://github.com/thin-edge/meta-tedge-project/actions.

A dedicated github runner will be used due to the builds taking such as long time (and requiring a large cache)

**Comment by reubenmiller** [comment]
The [meta-tedge-project](https://github.com/thin-edge/meta-tedge-project/actions) github actions are in place and build projects which use this layer now.
