### ISSUE TITLE
Check if Yocto can use "cargo fetch" command for dependencies

### ISSUE THREAD

**Issue by Bravo555** [thin-edge/meta-tedge#31]
The recipe update process is made unnecessarily more difficult by the requirement have all dependencies present in `SRC_URI` variable of the recipe. This makes it so when we want to change the revision used in the recipe, we have to do the following:

1. Edit the recipe version and revision
2. Manually check out this revision of the thin-edge.io repository
3. Run `cargo bitbake` on any crate in the workspace
4. Copy the dependencies section of the generated recipe into `dependencies.inc`
5. Run bitbake build

AFAIK this design is mainly the result of strong task separation common in legacy build systems. In the case of Yocto, it's because we're supposed to download all the necessary source code in the `do_fetch` task, and then unpack it in the `do_unpack` task, so the compilation in the `do_compile` task can be performed without the need to access the network.
The main issue is that without specifying all the crates in advance, we can't see what dependencies are present in `Cargo.lock` without unpacking the source code, as that would break the `do_fetch/do_unpack` separation.

However, I'd argue that while supporting `do_compile` without network access can be necessary in some settings, the separation of fetching and unpacking of source code only adds more complexity for little gains in disk space, so we should prioritise a simple solution over the space-optimal one.

To solve this issue, I propose modifying the `cargo` class, so that all code fetching and unpacking is performed in the `do_fetch` task. The task would have to perform the following steps:

1. Download the primary source archive of the recipe
2. Unpack all the source code instead of deferring it to `do_unpack` task
3. Use [`cargo fetch`](https://doc.rust-lang.org/cargo/commands/cargo-fetch.html) command to download the dependencies.

This solution sits between what meta-rust and meta packages are doing (require listing of all dependencies in the recipe file) and what meta-rust-bin is doing (just provide a `do_compile` task which has to access the network). By using `cargo fetch`, the dependencies can be downloaded and later compiled by cargo without having to access the network (using `cargo --offline` flag).

But this issue cannot be resolved in this repository only, the solution would have to be merged upstream to the providers of the `cargo` bitbake class, which are: meta-rust, meta-rust-bin, and meta layers. meta-rust and meta-rust-bin are hosted on Github, so contributing to them would be easiest.

Steps to complete:

- [ ] Research the viability of the solution - check if this topic was already discussed between the contributors of the relevant repositories, what are the possible tradeoff that they encountered that made them reject this design
- [ ] If the solution seems viable, implement it on a fork of meta-rust or meta-rust-bin
- [ ] Try to merge the solution into meta-rust or meta-rust-bin. If succeeded, the issue can be resolved on our end.
- [ ] Try to merge into the main poky repository. It would be harder because AFAIK it's not on Github and development happens using mailing lists and whatnot. However merging this improvement to core would probably make many people's lives easier so it wouldn't hurt to try. Also it would make the unmaintained cargo-bitbake tool unnecessary.

**Comment by Ruadhri17** [comment]
Solved with #43
