### ISSUE TITLE
tedge-state-scripts_1.0.bb always inherits mender-state-scripts

### ISSUE THREAD

**Issue by satel-kalletuulos** [thin-edge/meta-tedge#49]
The first line of recipes-tedge/tedge-state-scripts/tedge-state-scripts_1.0.bb content is:

`inherit mender-state-scripts`

This causes that meta-mender needs to be available even though meta-tedge would be used without Mender services. This was fixed easily by commenting the line away, but then, the inherit has to be done somewhere else in case Mender services are used.

**Comment by reubenmiller** [comment]
Thanks for posting the issue. You are also free to submit a PR if you want :)

**Comment by satel-kalletuulos** [comment]
Pull request submitted: https://github.com/thin-edge/meta-tedge/pull/50
