### ISSUE TITLE
Make core-image-tedge able to be run without systemd

### ISSUE THREAD

**Issue by Bravo555** [thin-edge/meta-tedge#65]
Currently `core-image-tedge` image requires `tedge-bootstrap` which requires systemd to be enabled. This needs to be relaxed so that `tedge-bootstrap` is not included if using sysvinit, or two separate images should be used.

              Yeah this recipe should be attached under condition that systemd is present. I misunderstood `REQUIRED_DISTRO_FEATURES` variable in yocto and I thought it will do it automatically.

_Originally posted by @Ruadhri17 in https://github.com/thin-edge/meta-tedge/pull/63#discussion_r1523628734_

**Comment by Ruadhri17** [comment]
Fixed in #63
